### ISSUE TITLE
Support multiple contexts

### ISSUE THREAD

**Issue by smpallen99** [ex-admin/ex_admin#35]
The concept of Talon contexts has been designed into the architecture, but has not been fully implemented yet. We generate a default context. We need to test a second context and ensure everything works with multiple contexts. 

The context abstraction is how you will support a talon managed front end and backend admin interface, for example. 

Here is how a context works:

* A set of talon resources are associated with a context
* Routes are scoped to a context
* Contexts can share themes or map do different themes

**Comment by dsnider** [comment]
Relatedly, I'd add:
- A given schema can be represented by more than one Talon resource providing different perspectives of that schema, even within a given Talon context. 
- A given Talon resource could be re-used across Talon contexts.

**Comment by smpallen99** [comment]
Currently, the context is bound to the resource file. That would have to be changed. Furthermore, there would need to be a run time association instead of the current compile time binding.

**Comment by smpallen99** [comment]
I believe I have the organizational structure design worked out. First some nomenclature: 

* theme - a UI layout including a layout, CRUD Phoenix templates, and UI assets including JS, CSS, Images, and fonts.
* concern - a Talon "Endpoint" or interface. For example, a Talon implementation with a separate admin backend and front end interfaces.

The current design is based on Talon managed Web UI with the following requirements:

* one or more concerns. For example, `Admin` and `FrontEnd`.
* one or more installed themes i.e `admin-lte`, `active_admin`,  and `admin-lte-topnav`
* theme configuration/customization is done based on concerns.
* two separate concerns can use the same theme, while customizing their individual layouts, CRUD templates, and custom actions.
* a single concern can have different themes with significantly different structure. For example, one Bootstrap based and the other Semantic UI based.
* themes should be selectable at runtime. 

The above requirements imposes a directory structure like:

* web/templates/talon/`concern name`/`theme name`/
  * layout
  * generators - CRUD template generators for all concern resources for the given theme
  * `resource name`/generators - CRUD generators for a specific resource
* web/views/talon/`concern name`/`theme name`

Additionally, the following ideas are open for discussion

* the `talon` folder structure is used to make it clear what directories/files are part of talon
* this adds an extra level of directories that may be seen as a complication
* the Talon project is a web concern
* a simplified directory structure could be:
  
  * lib/my_app/talon/
    * resources/`concern name`/
      * `concern name`.ex
      * `resource_name`.ex
    * templates/`concern name`/`template name`/
      * generators
      * `resource name`/generators/
    * controllers
    * views/`concern name`/`template name`/
      * ...
    * web.ex

**Comment by smpallen99** [comment]
complete and merged
