### ISSUE TITLE
Add travis to the project

### ISSUE THREAD

**Issue by smpallen99** [ex-admin/ex_admin#38]
Configure the project on travis to run tests.

**Comment by smpallen99** [comment]
Most of the work has been completed. However, I'm getting two test failures on travis that do not happen on my dev machine. I'm using `Mix.Tasks.Phx.New` in my mix tests to build test phoenix projects to test the talon installers. 

`Mix.Tasks.Phx.New` is part of the phoenix installer archive and not part of the phoenix dependency. The tests work on my dev machine since I have the phoenix installer archive. However the archive is not installed on travis, so these tests are failing on travis. 

I need to figure out how to install the archive on the travis build.

**Comment by ggpasqualino** [comment]
You may add the `mix archive.install ...` command just before the `mix test` in the script step, or in the before_script step as well.

You may check this [setup](https://github.com/nerves-project/nerves_system_rpi2/blob/master/.travis.yml#L41) from nerves project

**Comment by dsnider** [comment]
@smpallen99 Take a look at PR #91. After hacking around a bit, I noticed the wrong Phoenix archive was being installed. Travis builds now complete successfully.
