### ISSUE TITLE
Add dashboard support

### ISSUE THREAD

**Issue by dsnider** [ex-admin/ex_admin#40]
Add support for singular pages in general and a default dashboard landing page similar to ExAdmin.

* mix talon.new should add a default dashboard page
* implement a page controller
* document how pages work in Talon and how to use and customize them

**Comment by tmbb** [comment]
Could you expand a little more on this feature? What does it mean?

**Comment by smpallen99** [comment]
@tmbb Just added some notes to the description

**Comment by dsnider** [comment]
Closing this with the work merged with PR #55. Current related tickets include #72, #66, #64, #52, #69, #70 

@smpallen99 Let's use finer grained tickets for anything you feel remains.
