### ISSUE TITLE
Add gettext support

### ISSUE THREAD

**Issue by dsnider** [ex-admin/ex_admin#46]

**Comment by smpallen99** [comment]
Couple points about gettext support. 

- I like the idea olf having all talon messages use a "Talon" domain. That way all messages for Talon are grouped under the Talon domain. This is the approach we used for Coherence and I think it works we..
- All Talon generated code should import the project's Gettext module and use dgettext("Talon", ...)
- All gettext calls from the Talon library should use the messages backend file by calling a function on the backend. The Messages backend file  generated so it is compiled in the context of the project's source, so it can import the project's Gettext module.
- The messages backend file implements a behaviour. This ensures that if we add message functions on an upgrade and the use choose not to update their messages file, they will get compiler warnings indicating that there are missing functions based on the behaviour.
