### ISSUE TITLE
Provide capability to specify talon directory locations

### ISSUE THREAD

**Issue by smpallen99** [ex-admin/ex_admin#47]
@dsnider and I have been discussing this idea for a while. Here is a summary of what we have decided to do.

* specify the top level talon path. 
* specify the directory structure for each of the directories for `controllers`, `views`, `templates`

With these two options, the user has the option to create the following directory layouts:

* lib/my_app/web/talon/admin/ `controllers`, `views`, `templates`
* lib/my_app/web/ `talon/admin/controllers`, `talon/admin/views`, etc
* lib/my_app/talon/ `admin/controllers`, `admin/views`, etc
* lib/my_app/ `admin/controllers`, `admin/views`, `front_end/controllers`, `front_end/views`, etc
* `web/talon/...`

**Comment by tmbb** [comment]
As long as all talon specific features are under a directory named talon, I don't have any strong opinions.

**Comment by smpallen99** [comment]
Complete and merged
