### ISSUE TITLE
Change the default concern and route to admin

### ISSUE THREAD

**Issue by smpallen99** [ex-admin/ex_admin#48]
Currently the `talon.new` mix task creates the default concern as `MyProject.Talon` and the route prefix as `/talon`. @dsnider and I both feel that the default generated concern should be `MyProject.Admin` with a corresponding route prefix of `/admin`.

**Comment by tmbb** [comment]
I also think I prefer a route named "/admin" for my admin interface.

**Comment by smpallen99** [comment]
Work complete and merged
