### ISSUE TITLE
Typo in repository description?

### ISSUE THREAD

**Issue by tmbb** [ex-admin/ex_admin#51]
Currently it reads:

> An app builder framework for Phoenix. Formally, called ExAdmin 

Shouldn't it be:

> An app builder framework for Phoenix. Formerly called ExAdmin

**Comment by dsnider** [comment]
@tmbb I'm sure you'll find many such typos at this point! I changed it to: `An app builder framework for Phoenix, formally called ExAdmin.` but we'll probably change/expand that soon too.

**Comment by tmbb** [comment]
I'm sorry if I didn't make myself clear. The typo was that "formally" (= officially) should be "formerly" (= something that isn't like it used to be anymore). Or maybe "formally" has another meaning I'm not aware of.

**Comment by dsnider** [comment]
Ha, that indeed should be "formerly" -- fixed now!
