### ISSUE TITLE
Ensure resource action links/buttons don't wrap

### ISSUE THREAD

**Issue by dsnider** [ex-admin/ex_admin#54]
Use Bootstrap 3 `text-nowrap` on the container. 

![image](https://user-images.githubusercontent.com/16876/27097027-f51f3e4c-5040-11e7-8b3f-78d3a741650c.png)

**Comment by smpallen99** [comment]
The fix for this is in my current branch. I added a width to the css.

**Comment by dsnider** [comment]
I believe my branch has the width as well:

```css
table.index_table th.actions {
  width: 90px;
}
```
But it's too narrow, which highlights the maintenance problem with this approach of hardcoding widths. Even if increased, if the font size of the icon, padding, margin, etc. are somehow increased, it will again wrap. 

Using `white-space: nowrap` on the container is more robust. Bootstrap gives us that by adding the `text-nowrap` class on the container.

**Comment by smpallen99** [comment]
thats fine
