### ISSUE TITLE
Update slime dep version

### ISSUE THREAD

**Issue by smpallen99** [ex-admin/ex_admin#63]
We are currently pulling in version 0.16.0. Master is at 1.0.0. We should add an explicit dependency for 1.0.0. Hopefully this will resolve the compile warnings.

**Comment by dsnider** [comment]
Given the new warnings we're seeing (below) with Slime 1.0.0 and the compiler not running the first time, perhaps we should roll back this commit and let slime 1.0.0 gel for a bit? 

```elixir
slime 1.0.0
WARN:  Missing plugins: [rebar3_hex]
==> neotoma (compile)
==> fs (compile)
===> Compiling ranch
==> poolboy (compile)
===> Compiling cowlib
===> Compiling cowboy
'/Users/dsnider/Workspace/talonframework/talon_blog_demo/deps/slime/src/slime_parser_transform.erl' already exists, skipping generation.
==> slime
```

**Comment by smpallen99** [comment]
the talon compiler not running first time issue has been around for a long time. Nothing to do with the slime update. I believe the rebar3 warning is related to local hex setup. The slime_parser_transform.erl message isn't even a warning. Its a log message.

So, we traded a number of warning messages for 1 warning message. I don't see any reason to roll back
