### ISSUE TITLE
Default page template name should be index.html.slime not page_name.html.slime

### ISSUE THREAD

**Issue by smpallen99** [ex-admin/ex_admin#66]
The default template name should be something standard, not named after the page. Especially since its contained under a directory of the page name (view name). I believe there are two options here, either index or show. 

I would like the name to be index since that is typically the default name of a page under standard web practices. Furthermore, its the default get action (no ID) on the page's view.

**Comment by dsnider** [comment]
I agree. Shall I change now as implemented or as part of page generation integration into talon.gen.resource? (#52 / #64)

**Comment by smpallen99** [comment]
Yep, you change this when you'r in working on the other issues.

**Comment by dsnider** [comment]
See: https://github.com/talonframework/talon/pull/73/commits/862fedeb1bf17516e48fcad2345a5a02717ad8d2
