### ISSUE TITLE
Change default action on page controller

### ISSUE THREAD

**Issue by smpallen99** [ex-admin/ex_admin#70]
The default action name for the page controller should be something standard, not page. 

I suggest that it be index to align with the default template name from discussion in #66

**Comment by dsnider** [comment]
Phoenix doc example uses `:show` for this: https://hexdocs.pm/phoenix/Phoenix.Router.html

Should we go with that?

**Comment by smpallen99** [comment]
Our model is different than the example in the phoenix docs. We have a separate view for each page. Furthermore, I would like to see a separate controller for each page. So, I think the default action should be index. However, functionally it does not make much difference. If there is a strong argument to use show, I my change my opinion.

**Comment by dsnider** [comment]
I agree about the separate view being relevant. With a single page controller and a single view, I'd say to use a single template folder with the templates named by page.

With one controller and N views, we have a resource named template folder and either a show/index template. It's arguable with this scenario. My thought was to let the PageController index action handle the scenario when the page wasn't provided. I'm not overly wedded either way. Further, our decision on #71 may be impact this.

**Comment by dsnider** [comment]
Went with index action: https://github.com/talonframework/talon/pull/73/commits/862fedeb1bf17516e48fcad2345a5a02717ad8d2
